### ISSUE TITLE
Getting an error that has to do with your code, no idea why

### ISSUE THREAD

**Issue by theos-space** [jcabi/jcabi-xml#114]
```
Exception in thread "main" java.lang.NoClassDefFoundError: com/jcabi/immutable/ArrayMap
    at com.jcabi.xml.XPathContext.<init>(XPathContext.java:77)
    at com.jcabi.xml.XMLDocument.<init>(XMLDocument.java:155)
    at com.jcabi.xml.XMLDocument.<init>(XMLDocument.java:260)
    at space.theos.xmlparser.Main.main(Main.java:31)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke(Method.java:497)
    at com.intellij.rt.execution.application.AppMain.main(AppMain.java:144)
Caused by: java.lang.ClassNotFoundException: com.jcabi.immutable.ArrayMap
    at java.net.URLClassLoader.findClass(URLClassLoader.java:381)
    at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
    at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:331)
    at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
    ... 9 more

Process finished with exit code 1
```

I've already checked my code over a few times and there's nothing wrong with it, any ideas?

**Comment by dmarkov** [comment]
@yegor256 take a look at this issue please and dispatch it somehow, see [par.21](http://at.teamed.io/policy.html#21)

**Comment by yegor256** [comment]
@theos-space you need to add this dependency to classpath: jcabi-immutable (http://immutable.jcabi.com/)

**Comment by 0crat** [comment]
Oops! Job `gh:jcabi/jcabi-xml#114` was not in scope
