### ISSUE TITLE
A subsequent query on an XPath result doesn't work

### ISSUE THREAD

**Issue by Glusk** [jcabi/jcabi-xml#148]
I've run into a problem working with the library. I'm not entirely sure what's wrong, but [this test](https://github.com/Glusk2/jcabi-xml/pull/1/commits/a0bea4ad0c74005aaf7360c94469c99e896cb726) (minimized in this [commit](https://github.com/Glusk2/jcabi-xml/commit/785821b1a378db6e154925624f17b9613d62586f)) fails. Code in question:
``` Java
@Test
public void bug() throws Exception {
    final XML xml = new XMLDocument(
        "<r><p a='1'/><p a='2'/></r>"
    );
    MatcherAssert.assertThat(
        xml.nodes("//p")
           .get(1)
           .xpath("//p/@a")
           .get(0),
        Matchers.equalTo("2")
    );
}
```
produces this error:
```
java.lang.AssertionError: 

Expected: "2"
     but: was "1"
	at org.hamcrest.MatcherAssert.assertThat(MatcherAssert.java:20)
	at org.hamcrest.MatcherAssert.assertThat(MatcherAssert.java:8)
	at com.jcabi.xml.XMLDocumentTest.bug(XMLDocumentTest.java:472)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:47)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
	at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:325)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:78)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:57)
	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)
	at org.apache.maven.surefire.junitcore.pc.Scheduler$1.run(Scheduler.java:393)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
```
May be related to: #62

**Comment by 0crat** [comment]
@yegor256[/z](https://www.0crat.com/u/yegor256) please, pay attention to this issue

**Comment by 0crat** [comment]
@glusk2[/z](https://www.0crat.com/u/glusk2) this project will fix the problem faster if you donate a few dollars to it; just [click here](https://www.0crat.com/contrib/C3RUBL5H9) and pay via Stripe, it's very fast, convenient and appreciated; thanks a lot!
