### ISSUE TITLE
XSLDocumentTest#stripsXml() fails

### ISSUE THREAD

**Issue by simonjenga** [jcabi/jcabi-xml#151]
This test failure seems to have been fixed at #47 but it now looks like the issue has come up again.

```

C:\javaworkspace\jcabi-xml>mvn clean package
.
.
.
.
[?[2;37mDEBUG?[m] pool-1-thread-10 com.jcabi.xml.XSLDocument: net.sf.saxon.jaxp.TransformerImpl transformed XML
[?[2;37mDEBUG?[m] pool-1-thread-11 com.jcabi.xml.XSLDocument: net.sf.saxon.jaxp.TransformerImpl transformed XML
[?[2;37mDEBUG?[m] pool-1-thread-11 com.jcabi.xml.XSLDocument: net.sf.saxon.jaxp.TransformerImpl transformed XML
[?[2;37mDEBUG?[m] pool-1-thread-5 com.jcabi.xml.XSLDocument: net.sf.saxon.jaxp.TransformerImpl transformed XML
[?[0;31mERROR?[m] pool-1-thread-16 com.jcabi.xml.ConsoleErrorListener: #error(): oopsie...
[?[0;31mERROR?[m] pool-1-thread-16 com.jcabi.xml.ConsoleErrorListener: #fatalError(): Processing terminated by xsl:message at line 1 in file:///; SystemID: file:///; Line#: 1; Column#: 136
Tests run: 8, Failures: 1, Errors: 0, Skipped: 0, Time elapsed: 6.744 sec <<< FAILURE! - in com.jcabi.xml.XSLDocumentTest
stripsXml(com.jcabi.xml.XSLDocumentTest)  Time elapsed: 4.33 sec  <<< FAILURE!
java.lang.AssertionError:

Expected: a string containing "<a>\r\n   <b/>\r\n</a>"
     but: was "<?xml version="1.0" encoding="UTF-8"?>
<a>
   <b/>
</a>
"
        at org.hamcrest.MatcherAssert.assertThat(MatcherAssert.java:20)
        at org.hamcrest.MatcherAssert.assertThat(MatcherAssert.java:8)
        at com.jcabi.xml.XSLDocumentTest.stripsXml(XSLDocumentTest.java:157)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50)
        at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
        at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:47)
        at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
        at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:325)
        at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:78)
        at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:57)
        at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)
        at org.apache.maven.surefire.junitcore.pc.Scheduler$1.run(Scheduler.java:393)
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
        at java.util.concurrent.FutureTask.run(FutureTask.java:266)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
        at java.lang.Thread.run(Thread.java:748)

Running com.jcabi.xml.StrictXMLTest
SLF4J: The following loggers will not work because they were created
SLF4J: during the default configuration phase of the underlying logging system.
SLF4J: See also http://www.slf4j.org/codes.html#substituteLogger
SLF4J: com.jcabi.xml.StrictXML
SLF4J: com.jcabi.xml.XSDDocument
SLF4J: com.jcabi.xml.StrictXML
SLF4J: com.jcabi.xml.XSDDocument
SLF4J: com.jcabi.xml.StrictXML
SLF4J: com.jcabi.xml.XSDDocument
SLF4J: com.jcabi.xml.XSDDocument
SLF4J: com.jcabi.xml.XSDDocument
SLF4J: com.jcabi.xml.StrictXML
SLF4J: com.jcabi.xml.XSDDocument
SLF4J: com.jcabi.xml.XSDDocument
SLF4J: com.jcabi.xml.XSDDocument
SLF4J: com.jcabi.xml.XSDDocument
SLF4J: com.jcabi.xml.XSDDocument
SLF4J: com.jcabi.xml.XSDDocument
SLF4J: com.jcabi.xml.StrictXML
SLF4J: com.jcabi.xml.XSDDocument
SLF4J: com.jcabi.xml.StrictXML
SLF4J: com.jcabi.xml.XSDDocument
SLF4J: com.jcabi.xml.StrictXML
SLF4J: com.jcabi.xml.XSDDocument
SLF4J: com.jcabi.xml.StrictXML
SLF4J: com.jcabi.xml.XSDDocument
SLF4J: com.jcabi.xml.StrictXML
SLF4J: com.jcabi.xml.XSDDocument
SLF4J: com.jcabi.xml.StrictXML
SLF4J: com.jcabi.xml.XSDDocument
SLF4J: com.jcabi.xml.StrictXML
SLF4J: com.jcabi.xml.XSDDocument
SLF4J: com.jcabi.xml.StrictXML
SLF4J: com.jcabi.xml.XSDDocument
SLF4J: com.jcabi.xml.StrictXML
SLF4J: com.jcabi.xml.XSDDocument
SLF4J: com.jcabi.xml.StrictXML
SLF4J: com.jcabi.xml.XSDDocument
SLF4J: com.jcabi.xml.XSDDocument
SLF4J: com.jcabi.xml.XSDDocument
SLF4J: com.jcabi.xml.StrictXML
SLF4J: com.jcabi.xml.XSDDocument
SLF4J: com.jcabi.xml.XSDDocument
SLF4J: com.jcabi.xml.XSDDocument
SLF4J: com.jcabi.xml.XSDDocument
SLF4J: com.jcabi.xml.XSDDocument
SLF4J: com.jcabi.xml.XSDDocument
SLF4J: com.jcabi.xml.StrictXML
SLF4J: com.jcabi.xml.XSDDocument
SLF4J: com.jcabi.xml.StrictXML
SLF4J: com.jcabi.xml.XSDDocument
SLF4J: com.jcabi.xml.XSDDocument
SLF4J: com.jcabi.xml.XSDDocument
SLF4J: com.jcabi.xml.XSDDocument
SLF4J: com.jcabi.xml.StrictXML
SLF4J: com.jcabi.xml.XSDDocument
SLF4J: com.jcabi.xml.StrictXML
SLF4J: com.jcabi.xml.XSDDocument
SLF4J: com.jcabi.xml.StrictXML
SLF4J: com.jcabi.xml.XSDDocument
SLF4J: com.jcabi.xml.XSDDocument
SLF4J: com.jcabi.xml.XSDDocument
SLF4J: com.jcabi.xml.StrictXML
SLF4J: com.jcabi.xml.XSDDocument
SLF4J: com.jcabi.xml.StrictXML
SLF4J: com.jcabi.xml.XSDDocument
SLF4J: com.jcabi.xml.StrictXML
SLF4J: com.jcabi.xml.XSDDocument
SLF4J: com.jcabi.xml.StrictXML
SLF4J: com.jcabi.xml.XSDDocument
SLF4J: com.jcabi.xml.StrictXML
SLF4J: com.jcabi.xml.XSDDocument
SLF4J: com.jcabi.xml.StrictXML
SLF4J: com.jcabi.xml.XSDDocument
SLF4J: com.jcabi.xml.StrictXML
SLF4J: com.jcabi.xml.XSDDocument
SLF4J: com.jcabi.xml.StrictXML
SLF4J: com.jcabi.xml.XSDDocument
SLF4J: com.jcabi.xml.StrictXML
SLF4J: com.jcabi.xml.XSDDocument
SLF4J: com.jcabi.xml.StrictXML
SLF4J: com.jcabi.xml.XSDDocument
SLF4J: com.jcabi.xml.StrictXML
SLF4J: com.jcabi.xml.XSDDocument
SLF4J: com.jcabi.xml.StrictXML
SLF4J: com.jcabi.xml.XSDDocument
SLF4J: com.jcabi.xml.StrictXML
SLF4J: com.jcabi.xml.XSDDocument
SLF4J: com.jcabi.xml.StrictXML
SLF4J: com.jcabi.xml.XSDDocument
SLF4J: com.jcabi.xml.StrictXML
SLF4J: com.jcabi.xml.XSDDocument
SLF4J: com.jcabi.xml.StrictXML
SLF4J: com.jcabi.xml.XSDDocument
SLF4J: com.jcabi.xml.StrictXML
SLF4J: com.jcabi.xml.XSDDocument
SLF4J: com.jcabi.xml.StrictXML
SLF4J: com.jcabi.xml.XSDDocument
SLF4J: com.jcabi.xml.StrictXML
SLF4J: com.jcabi.xml.XSDDocument
SLF4J: com.jcabi.xml.StrictXML
SLF4J: com.jcabi.xml.XSDDocument
SLF4J: com.jcabi.xml.StrictXML
SLF4J: com.jcabi.xml.XSDDocument
SLF4J: com.jcabi.xml.StrictXML
SLF4J: com.jcabi.xml.XSDDocument
SLF4J: com.jcabi.xml.StrictXML
SLF4J: com.jcabi.xml.XSDDocument
SLF4J: com.jcabi.xml.StrictXML
SLF4J: com.jcabi.xml.XSDDocument
SLF4J: com.jcabi.xml.StrictXML
SLF4J: com.jcabi.xml.XSDDocument
SLF4J: com.jcabi.xml.StrictXML
SLF4J: com.jcabi.xml.XSDDocument
SLF4J: com.jcabi.xml.XSDDocument
SLF4J: com.jcabi.xml.StrictXML
SLF4J: com.jcabi.xml.StrictXML
SLF4J: com.jcabi.xml.XSDDocument
SLF4J: com.jcabi.xml.StrictXML
SLF4J: com.jcabi.xml.XSDDocument
SLF4J: com.jcabi.xml.StrictXML
SLF4J: com.jcabi.xml.XSDDocument
SLF4J: com.jcabi.xml.StrictXML
SLF4J: com.jcabi.xml.XSDDocument
SLF4J: com.jcabi.xml.StrictXML
[?[2;37mDEBUG?[m] pool-1-thread-3 com.jcabi.xml.XSDDocument: org.apache.xerces.jaxp.validation.SimpleXMLSchema detected 2 error(s)
[?[0;33mWARN?[m] pool-1-thread-3 com.jcabi.xml.StrictXML: 2 XML validation error(s):
  -1:-1: cvc-datatype-valid.1.2.1: 'not an integer' is not a valid value for 'integer'.
  -1:-1: cvc-type.3.1.3: The value 'not an integer' of element 'root' is not valid.
<?xml version="1.0" encoding="UTF-8"?>
<root>not an integer</root>

[?[0;31mERROR?[m] pool-1-thread-6 com.jcabi.xml.StrictXML: Try #1 of 3 failed: java.net.SocketException: Attempt #1 failed
[?[0;31mERROR?[m] pool-1-thread-6 com.jcabi.xml.StrictXML: Try #2 of 3 failed: java.net.SocketException: Attempt #2 failed
[?[0;33mWARN?[m] pool-1-thread-2 com.jcabi.xml.StrictXML: 1 XML validation error(s):
  -1:-1: cvc-complex-type.2.4.a: Invalid content was found starting with element 'notValidElement'. One of '{"http://maven.apache.org/POM/4.0.0":modelVersion, "http://maven.apache.org/POM/4.0.0":parent, "http://maven.apache.org/POM/4.0.0":groupId, "http://maven.apache.org/POM/4.0.0":artifactId, "http://maven.apache.org/POM/4.0.0":version, "http://maven.apache.org/POM/4.0.0":packaging, "http://maven.apache.org/POM/4.0.0":name, "http://maven.apache.org/POM/4.0.0":description, "http://maven.apache.org/POM/4.0.0":url, "http://maven.apache.org/POM/4.0.0":inceptionYear, "http://maven.apache.org/POM/4.0.0":organization, "http://maven.apache.org/POM/4.0.0":licenses, "http://maven.apache.org/POM/4.0.0":developers, "http://maven.apache.org/POM/4.0.0":contributors, "http://maven.apache.org/POM/4.0.0":mailingLists, "http://maven.apache.org/POM/4.0.0":prerequisites, "http://maven.apache.org/POM/4.0.0":modules, "http://maven.apache.org/POM/4.0.0":scm, "http://maven.apache.org/POM/4.0.0":issu
ment, "http://maven.apache.org/POM/4.0.0":ciManagement, "http://maven.apache.org/POM/4.0.0":distributionManagement, "http://maven.apache.org/POM/4.0.0":properties, "http://maven.apache.org/POM/4.0.0":dependencyManagement, "http://maven.apache.org/POM/4.0.0":dependencies, "http://maven.apache.org/POM/4.0.0":repositories, "http://maven.apache.org/POM/4.0.0":pluginRepositories, "http://maven.apache.org/POM/4.0.0":build, "http://maven.apache.org/POM/4.0.0":reports, "http://maven.apache.org/POM/4.0.0":reporting, "http://maven.apache.org/POM/4.0.0":profiles}' is expected.
<?xml version="1.0" encoding="UTF-8"?>
<!--
Copyright (c) 2012-2017, jcabi.com
All rights reserved.

Redistribution and use in source and binary forms, with or without
modification, are permitted provided that the following conditions
are met: 1) Redistributions of source code must retain the above
copyright notice, this list of conditions and the following
disclaimer. 2) Redistributions in binary form must reproduce the above
copyright notice, this list of conditions and the following
disclaimer in the documentation and/or other materials provided
with the distribution. 3) Neither the name of the jcabi.com nor
the names of its contributors may be used to endorse or promote
products derived from this software without specific prior written
permission.

THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS
"AS IS" AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT
NOT LIMITED TO, THE IMPLIED WARRANTIES OF MERCHANTABILITY AND
FITNESS FOR A PARTICULAR PURPOSE ARE DISCLAIMED. IN NO EVENT SHALL
THE COPYRIGHT HOLDER OR CONTRIBUTORS BE LIABLE FOR ANY DIRECT,
INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES
(INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR
SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION)
HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT,
STRICT LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE)
ARISING IN ANY WAY OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED
OF THE POSSIBILITY OF SUCH DAMAGE.
-->
<project xmlns="http://maven.apache.org/POM/4.0.0"
         xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
  <notValidElement/>
</project>

Tests run: 9, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 28.534 sec - in com.jcabi.xml.StrictXMLTest
Running com.jcabi.xml.XMLDocumentTest
Tests run: 20, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 2.724 sec - in com.jcabi.xml.XMLDocumentTest
Running com.jcabi.xml.XPathContextTest
Tests run: 5, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 0.062 sec - in com.jcabi.xml.XPathContextTest
Picked up JAVA_TOOL_OPTIONS: -Dfile.encoding=UTF-8

Results :

Failed tests:
  XSLDocumentTest.stripsXml:157
Expected: a string containing "<a>\r\n   <b/>\r\n</a>"
     but: was "<?xml version="1.0" encoding="UTF-8"?>
<a>
   <b/>
</a>
"

Tests run: 59, Failures: 1, Errors: 0, Skipped: 0

[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 01:51 min
[INFO] Finished at: 2019-02-18T16:50:40
[INFO] Final Memory: 45M/628M
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal org.apache.maven.plugins:maven-surefire-plugin:2.19.1:test (default-test) on project jcabi-xml: There are test failures.
[ERROR]
[ERROR] Please refer to C:\javaworkspace\jcabi-xml\target\surefire-reports for the individual test results.
[ERROR] -> [Help 1]
[ERROR]
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR]
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/MojoFailureException
C:\javaworkspace\jcabi-xml>
```

**Comment by 0crat** [comment]
@yegor256[/z](https://www.0crat.com/u/yegor256) please, pay attention to this issue

**Comment by 0crat** [comment]
@simonjenga[/z](https://www.0crat.com/u/simonjenga) this project will fix the problem faster if you donate a few dollars to it; just [click here](https://www.0crat.com/contrib/C3RUBL5H9) and pay via Stripe, it's very fast, convenient and appreciated; thanks a lot!

**Comment by yegor256** [comment]
@simonjenga fixed
