### ISSUE TITLE
`XSLDocument` is not thread-safe

### ISSUE THREAD

**Issue by mximp** [jcabi/jcabi-xml#185]
The following code fails:
```
      final XSL xsl =
          new XSLDocument(
              this.getClass().getResourceAsStream("/org/eolang/parser/optimize/globals-to-abstracts.xsl")
          ).with(new ClasspathSources());
      final List<Callable<Object>> tasks = new ArrayList<>(10);
      final List<Exception> exceptions = Collections.synchronizedList(new ArrayList<>(0));
      IntStream.range(1, 11)
          .forEach( i ->
              tasks.add(Executors.callable( () -> {
                  try {
                      xsl.transform(
                          new XMLDocument(
                              Paths.get(
                                  this.getClass().getResource("/valid-xml-in-classpath.xml").toURI())));
                  } catch (Exception e) {
                      exceptions.add(e);
                  }
              }))
          );
      do {
          Executors.newFixedThreadPool(10).invokeAll(tasks);
      } while (exceptions.isEmpty());
      if (!exceptions.isEmpty()) {
          exceptions.forEach(Throwable::printStackTrace);
          throw new IllegalStateException(exceptions.toString());
      }
```
Exception thrown:
```
java.lang.IllegalArgumentException: Failed to transform by net.sf.saxon.jaxp.TransformerImpl: [] (org.w3c.dom.DOMException: HIERARCHY_REQUEST_ERR: An attempt was made to insert a node where it is not permitted.; SystemID: file:///; Line#: 54; Column#: 35)
	at com.jcabi.xml.XSLDocument.transformInto(XSLDocument.java:411)
	at com.jcabi.xml.XSLDocument.transform(XSLDocument.java:371)
	at org.eolang.maven.OptimizeMojoTest.lambda$testTemp$1(OptimizeMojoTest.java:281)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:539)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
	at java.base/java.lang.Thread.run(Thread.java:833)
Caused by: net.sf.saxon.trans.XPathException: org.w3c.dom.DOMException: HIERARCHY_REQUEST_ERR: An attempt was made to insert a node where it is not permitted.
	at net.sf.saxon.dom.DOMWriter.startElement(DOMWriter.java:192)
	at net.sf.saxon.event.ProxyReceiver.startElement(ProxyReceiver.java:140)
	at net.sf.saxon.event.SequenceNormalizer.startElement(SequenceNormalizer.java:85)
	at net.sf.saxon.event.RegularSequenceChecker.startElement(RegularSequenceChecker.java:380)
	at net.sf.saxon.event.ComplexContentOutputter.startContent(ComplexContentOutputter.java:779)
	at net.sf.saxon.event.ComplexContentOutputter.characters(ComplexContentOutputter.java:269)
	at net.sf.saxon.expr.instruct.Copy.processLeavingTail(Copy.java:453)
	at net.sf.saxon.expr.instruct.TemplateRule.applyLeavingTail(TemplateRule.java:392)
	at net.sf.saxon.trans.Mode.applyTemplates(Mode.java:551)
	at net.sf.saxon.expr.instruct.ApplyTemplates.apply(ApplyTemplates.java:360)
	at net.sf.saxon.expr.instruct.ApplyTemplates.process(ApplyTemplates.java:294)
	at net.sf.saxon.expr.instruct.ElementCreator.processLeavingTail(ElementCreator.java:357)
	at net.sf.saxon.expr.instruct.Copy.processLeavingTail(Copy.java:437)
	at net.sf.saxon.expr.instruct.TemplateRule.applyLeavingTail(TemplateRule.java:392)
	at net.sf.saxon.trans.Mode.applyTemplates(Mode.java:551)
	at net.sf.saxon.trans.rules.TextOnlyCopyRuleSet.process(TextOnlyCopyRuleSet.java:72)
	at net.sf.saxon.trans.Mode.applyTemplates(Mode.java:524)
	at net.sf.saxon.trans.XsltController.applyTemplates(XsltController.java:685)
	at net.sf.saxon.s9api.AbstractXsltTransformer.applyTemplatesToSource(AbstractXsltTransformer.java:422)
	at net.sf.saxon.s9api.XsltTransformer.transform(XsltTransformer.java:355)
	at net.sf.saxon.jaxp.TransformerImpl.transform(TransformerImpl.java:75)
	at com.jcabi.xml.XSLDocument.transformInto(XSLDocument.java:408)
	... 7 more
Caused by: org.w3c.dom.DOMException: HIERARCHY_REQUEST_ERR: An attempt was made to insert a node where it is not permitted.
	at java.xml/com.sun.org.apache.xerces.internal.dom.CoreDocumentImpl.insertBefore(CoreDocumentImpl.java:439)
	at java.xml/com.sun.org.apache.xerces.internal.dom.NodeImpl.appendChild(NodeImpl.java:230)
	at net.sf.saxon.dom.DOMWriter.startElement(DOMWriter.java:157)
	... 28 more
```

**Comment by 0crat** [comment]
@yegor256[/z](https://www.0crat.com/u/yegor256) everybody who has role `DEV` is banned at [#185](https://github.com/jcabi/jcabi-xml/issues/185); I won't be able to assign anyone automatically; consider assigning someone manually (as in [§19](http://www.zerocracy.com/policy.html#19)), or invite more people (as in [§51](http://www.zerocracy.com/policy.html#51)), or remove the job from the scope (as in [§14](http://www.zerocracy.com/policy.html#14))

**Comment by 0crat** [comment]
@yegor256[/z](https://www.0crat.com/u/yegor256) everybody who has role `DEV` is banned at [#185](https://github.com/jcabi/jcabi-xml/issues/185); I won't be able to assign anyone automatically; consider assigning someone manually (as in [§19](http://www.zerocracy.com/policy.html#19)), or invite more people (as in [§51](http://www.zerocracy.com/policy.html#51)), or remove the job from the scope (as in [§14](http://www.zerocracy.com/policy.html#14))

**Comment by 0crat** [comment]
@yegor256[/z](https://www.0crat.com/u/yegor256) everybody who has role `DEV` is banned at [#185](https://github.com/jcabi/jcabi-xml/issues/185); I won't be able to assign anyone automatically; consider assigning someone manually (as in [§19](http://www.zerocracy.com/policy.html#19)), or invite more people (as in [§51](http://www.zerocracy.com/policy.html#51)), or remove the job from the scope (as in [§14](http://www.zerocracy.com/policy.html#14))

**Comment by yegor256** [comment]
@mximp I added a test in 614eb9a, but it doesn't find a bug. Are you sure there is a problem in jcabi-xml?

**Comment by mximp** [comment]
@yegor256 your test runs only once. This concurrent issue is not stable, hence in my version I added loop until exception is thrown. I checked your test with multiple executions and it resulted in the same error:
```
final XSL xsl = new XSLDocument(
            this.getClass().getResourceAsStream("/org/eolang/parser/xttool/transform.xsl")
        ).with(new ClasspathSources());
        final XML xml = new XMLDocument(
            this.getClass().getResourceAsStream("/org/eolang/parser/xttool/input.xml")
        );
        do {
            final AtomicInteger done = new AtomicInteger(0);
            final CountDownLatch latch = new CountDownLatch(1);
            final int total = 10;
            final ExecutorService exec = Executors.newFixedThreadPool(total);
            for (int task = 0; task < 10; ++task) {
                exec.submit(
                    () -> {
                        latch.await();
                        try {
                            xsl.transform(xml);
                        } catch (final Exception ex) {
                            ex.printStackTrace();
                        }
                        done.incrementAndGet();
                        return 0;
                    }
                );
            }
            latch.countDown();
            exec.shutdown();
            exec.awaitTermination(1L, TimeUnit.MINUTES);
            MatcherAssert.assertThat(done.get(), Matchers.equalTo(total));
        } while (true);
```

**Comment by yegor256** [comment]
@rultor release, tag is `0.25.5`

**Comment by yegor256** [comment]
@mximp it's released as 0.25.5

**Comment by mximp** [comment]
@yegor256 I guess it's not due to exception above. Also I don't see relevant tag in the repo.

**Comment by yegor256** [comment]
@mximp it was released, but site publishing failed. See https://repo.maven.apache.org/maven2/com/jcabi/jcabi-xml/

**Comment by mximp** [comment]
@yegor256 got it. thanks

**Comment by 0crat** [comment]
Job `gh:jcabi/jcabi-xml#185` is not assigned, can't get performer
