### ISSUE TITLE
Can't run IndexesRequestsTest.retrievesIndexFromSibling in IntelliJ on Windows

### ISSUE THREAD

**Issue by dpisarenko** [jcabi/jcabi-xml#38]
When I try to run the test `com.rultor.agents.github.IndexesRequestsTest.retrievesIndexFromSibling` in IntelliJ Idea 13 on Windows 7, the test fails with the following exception:

```
java.lang.ExceptionInInitializerError
	at com.rultor.spi.Talks$InDir.create(Talks.java:187)
	at com.rultor.agents.github.IndexesRequestsTest.retrievesIndexFromSibling(IndexesRequestsTest.java:106)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:47)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
	at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:325)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:78)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:57)
	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288)
	at org.junit.runners.ParentRunner.access$000(ParentRunner.java:58)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:363)
	at org.junit.runner.JUnitCore.run(JUnitCore.java:137)
	at com.intellij.junit4.JUnit4IdeaTestRunner.startRunnerWithArgs(JUnit4IdeaTestRunner.java:74)
	at com.intellij.rt.execution.junit.JUnitStarter.prepareStreamsAndStart(JUnitStarter.java:202)
	at com.intellij.rt.execution.junit.JUnitStarter.main(JUnitStarter.java:65)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at com.intellij.rt.execution.application.AppMain.main(AppMain.java:120)
Caused by: java.lang.RuntimeException: XPathFactory#newInstance() failed to create an XPathFactory for the default object model: http://java.sun.com/jaxp/xpath/dom with the XPathFactoryConfigurationException: javax.xml.xpath.XPathFactoryConfigurationException: java.util.ServiceConfigurationError: javax.xml.xpath.XPathFactory: jar:file:/C:/Users/DP118M/.m2/repository/net/sourceforge/saxon/saxon/9.1.0.8/saxon-9.1.0.8-xpath.jar!/META-INF/services/javax.xml.xpath.XPathFactory:2: Illegal configuration-file syntax
	at javax.xml.xpath.XPathFactory.newInstance(XPathFactory.java:102)
	at com.jcabi.xml.XMLDocument.<clinit>(XMLDocument.java:84)
	... 28 more
```

Please make sure that all tests in `com.rultor.agents.github.IndexesRequestsTest` can be run both via Maven and from the IDE.

**Comment by dmarkov** [comment]
I'll ask someone to take care of this task soon

**Comment by dmarkov** [comment]
@apocarteres this ticket is yours now, please proceed, and keep in mind [this](http://www.xdsd.org/2014/04/17/how-xdsd-is-different.html). Any technical questions you should ask right here

Budget here is **30 mins** (keep [this principle](http://www.xdsd.org/2014/04/17/how-xdsd-is-different.html) in mind)

**Comment by dmarkov** [comment]
@dpisarenko thanks for this report, I added 15 mins to your account, in transaction `49719999`

**Comment by apocarteres** [comment]
ok.got it

**Comment by apocarteres** [comment]
i'm sorry for silly question, but there did u find class <code>com.rultor.agents.github.IndexesRequestsTest</code> ? 
There is no such class in this repo

**Comment by dpisarenko** [comment]
It's part of the rultor project - https://github.com/yegor256/rultor/blob/master/src/test/java/com/rultor/agents/github/IndexesRequestsTest.java    03.01.2015, 19:42, "Alexander Paderin" <notifications@github.com>:i'm sorry for silly question, but there did u find class com.rultor.agents.github.IndexesRequestsTest ?  There is no such class in this repo—Reply to this email directly or view it on GitHub.

**Comment by apocarteres** [comment]
can't reproduce it yet, but faced another build fail culprit #701

**Comment by apocarteres** [comment]
btw, can you supply your <code>mvn --version</code>  pls? Does ypur IDE Maven plugin point  to system Maven installation, or probably you have several Maven installations? If so, provide all environments for them please

**Comment by dmarkov** [comment]
@apocarteres you're holding this ticket for 11 days already. If it's not finished (and closed) in the next 48 hours, it will be re-assigned to someone else, see [No Obligations](http://www.xdsd.org/2014/04/13/no-obligations-principle.html) principle... -30 added to your rating, at the moment it is: [+30](http://www.netbout.com/b/35111?open=rating)

**Comment by apocarteres** [comment]
it's duplicate of #654. try to run it under Java7 to confirm that it will be success

**Comment by apocarteres** [comment]
@dpisarenko it's duplicate of #654. try to run it under Java7 to confirm that it will be success

**Comment by dpisarenko** [comment]
Yes, with Java 7 it seems to work.

**Comment by dmarkov** [comment]
@apocarteres Thanks a lot, I just topped your account for **30 mins**, transaction ID `50519745`

added +30 to your rating, now it is equal to [+30](http://www.netbout.com/b/35111?open=rating)
