### ISSUE TITLE
Test XSLDocumentTest.stripsXml doesn't complete in AppVeyor

### ISSUE THREAD

**Issue by pinaf** [jcabi/jcabi-xml#44]
Possibly caused by the \n character in a Windows environment.
```
java.lang.AssertionError: 
Expected: a string containing "<a>\n<b/>\n</a>"
     but: was "<?xml version="1.0" encoding="UTF-8" standalone="no"?>
<a>
<b/>
</a>
"
    at org.hamcrest.MatcherAssert.assertThat(MatcherAssert.java:20)
    at org.hamcrest.MatcherAssert.assertThat(MatcherAssert.java:8)
    at com.jcabi.xml.XSLDocumentTest.stripsXml(XSLDocumentTest.java:142)
```

See [log](https://ci.appveyor.com/project/yegor256/jcabi-xml/build/6).

**Comment by dmarkov** [comment]
@yegor256 please do something about this issue

**Comment by yegor256** [comment]
@pinaf it's passing now at appveyor... looks like this issue is outdated. closing
