### ISSUE TITLE
Illegal character in path at index 19: file://C:/Documents and Settings/JustUser/.m2/repository/com/ jcabi/jcabi-aspects/0.20.1/jcabi-aspects-0.20.1.jar on Windows / Java7

### ISSUE THREAD

**Issue by apocarteres** [jcabi/jcabi-xml#49]
<pre>
[INFO] -------------------------------------------------
[INFO] Build Summary:
[INFO]   Passed: 2, Failed: 0, Errors: 0, Skipped: 0
[INFO] -------------------------------------------------
[INFO]
[INFO] --- qulice-maven-plugin:0.10:check (jcabi-check) @ jcabi-xml ---
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 03:50 min
[INFO] Finished at: 2015-01-21T18:22:29+03:00
[INFO] Final Memory: 29M/247M
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal com.qulice:qulice-maven-plugin:0.10:check (jcabi-check) on project jcabi-xml: Execution jcabi-check of goal c
om.qulice:qulice-maven-plugin:0.10:check failed: Illegal character in path at index 19: file://C:/Documents and Settings/JustUser/.m2/reposi
tory/com/jcabi/jcabi-aspects/0.20.1/jcabi-aspects-0.20.1.jar -> [Help 1]
org.apache.maven.lifecycle.LifecycleExecutionException: Failed to execute goal com.qulice:qulice-maven-plugin:0.10:check (jcabi-check) on pr
oject jcabi-xml: Execution jcabi-check of goal com.qulice:qulice-maven-plugin:0.10:check failed: Illegal character in path at index 19: file
://C:/Documents and Settings/JustUser/.m2/repository/com/jcabi/jcabi-aspects/0.20.1/jcabi-aspects-0.20.1.jar
        at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:224)
        at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:153)
        at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:145)
        at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:116)
        at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:80)
        at org.apache.maven.lifecycle.internal.builder.singlethreaded.SingleThreadedBuilder.build(SingleThreadedBuilder.java:51)
        at org.apache.maven.lifecycle.internal.LifecycleStarter.execute(LifecycleStarter.java:120)
        at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:355)
        at org.apache.maven.DefaultMaven.execute(DefaultMaven.java:155)
        at org.apache.maven.cli.MavenCli.execute(MavenCli.java:584)
        at org.apache.maven.cli.MavenCli.doMain(MavenCli.java:216)
        at org.apache.maven.cli.MavenCli.main(MavenCli.java:160)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:606)
        at org.codehaus.plexus.classworlds.launcher.Launcher.launchEnhanced(Launcher.java:289)
        at org.codehaus.plexus.classworlds.launcher.Launcher.launch(Launcher.java:229)
        at org.codehaus.plexus.classworlds.launcher.Launcher.mainWithExitCode(Launcher.java:415)
        at org.codehaus.plexus.classworlds.launcher.Launcher.main(Launcher.java:356)
Caused by: org.apache.maven.plugin.PluginExecutionException: Execution jcabi-check of goal com.qulice:qulice-maven-plugin:0.10:check failed:
 Illegal character in path at index 19: file://C:/Documents and Settings/JustUser/.m2/repository/com/jcabi/jcabi-aspects/0.20.1/jcabi-aspect
s-0.20.1.jar
        at org.apache.maven.plugin.DefaultBuildPluginManager.executeMojo(DefaultBuildPluginManager.java:143)
        at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:208)
        ... 19 more
Caused by: java.lang.IllegalArgumentException: Illegal character in path at index 19: file://C:/Documents and Settings/JustUser/.m2/reposito
ry/com/jcabi/jcabi-aspects/0.20.1/jcabi-aspects-0.20.1.jar
        at java.net.URI.create(URI.java:859)
        at com.qulice.maven.DefaultMavenEnvironment.classloader(DefaultMavenEnvironment.java:152)
        at com.qulice.checkstyle.CheckstyleValidator.validate(CheckstyleValidator.java:81)
        at com.qulice.maven.CheckMojo.run(CheckMojo.java:83)
        at com.qulice.maven.CheckMojo.doExecute(CheckMojo.java:59)
        at com.qulice.maven.AbstractQuliceMojo.execute(AbstractQuliceMojo.java:175)
        at org.apache.maven.plugin.DefaultBuildPluginManager.executeMojo(DefaultBuildPluginManager.java:132)
        ... 20 more
Caused by: java.net.URISyntaxException: Illegal character in path at index 19: file://C:/Documents and Settings/JustUser/.m2/repository/com/
jcabi/jcabi-aspects/0.20.1/jcabi-aspects-0.20.1.jar
        at java.net.URI$Parser.fail(URI.java:2829)
        at java.net.URI$Parser.checkChars(URI.java:3002)
        at java.net.URI$Parser.parseHierarchical(URI.java:3086)
        at java.net.URI$Parser.parse(URI.java:3034)
        at java.net.URI.<init>(URI.java:595)
        at java.net.URI.create(URI.java:857)
        ... 26 more
[ERROR]
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR]
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/PluginExecutionException
Z:\jcabi-xml>
</pre>

**Comment by yegor256** [comment]
@apocarteres how can I reproduce it?

**Comment by apocarteres** [comment]
just kick off <code>mvn -e clean install -Pqulice</code> on WIndows box

**Comment by dmarkov** [comment]
we'll find someone to do this task, soon

**Comment by dmarkov** [comment]
@apocarteres many thanks for the report, I topped your account for 15 mins, transaction 50596229

**Comment by dmarkov** [comment]
@maurezen it's your task, go ahead

**Comment by maurezen** [comment]
@dmarkov @yegor256 this is a known problem of creating an URI containing a space. The problem is in qulice, created an issue here, on which I depend: teamed/qulice#397

**Comment by maurezen** [comment]
@yegor256 any comments? do you approve the dependency?

**Comment by maurezen** [comment]
@yegor256 any comments?

**Comment by yegor256** [comment]
@dmarkov we need some more time here, we depend on a qulice bug

**Comment by dmarkov** [comment]
> @dmarkov we need some more time here, we depend on a qulice bug

@yegor256 right, take your time and thanks for informing

**Comment by maurezen** [comment]
@apocarteres I believe that the problem was fixed when parent artefact version was changed to 1.17 (and therefore qulice dependency version was changed to 0.12) on 24.02. Could you please check that this is indeed the case and if so, close the issue?
