### ISSUE TITLE
StrictXML throws NullPointerException if xsi:schemaLocation attr is not specified

### ISSUE THREAD

**Issue by carlosmiranda** [jcabi/jcabi-xml#94]
The following test fails with a `NullPointerException`:
```java
    @Test(expected = IllegalArgumentException.class)
    public void failsValidation() throws Exception {
        new StrictXML(
            new XMLDocument("<a></a>")
        );
    }
```

We get the following error trace:
```
java.lang.Exception: Unexpected exception, expected<java.lang.IllegalArgumentException> but was<java.lang.NullPointerException>
	at org.junit.internal.runners.statements.ExpectException.evaluate(ExpectException.java:28)
	at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:325)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:78)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:57)
	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288)
	at org.junit.runners.ParentRunner.access$000(ParentRunner.java:58)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:363)
	at org.eclipse.jdt.internal.junit4.runner.JUnit4TestReference.run(JUnit4TestReference.java:86)
	at org.eclipse.jdt.internal.junit.runner.TestExecution.run(TestExecution.java:38)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:459)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:675)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.run(RemoteTestRunner.java:382)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.main(RemoteTestRunner.java:192)
Caused by: java.lang.NullPointerException
	at sun.misc.MetaIndex.mayContain(MetaIndex.java:242)
	at sun.misc.URLClassPath$JarLoader.getResource(URLClassPath.java:995)
	at sun.misc.URLClassPath.getResource(URLClassPath.java:212)
	at sun.misc.URLClassPath.getResource(URLClassPath.java:265)
	at java.lang.ClassLoader.getBootstrapResource(ClassLoader.java:1261)
	at java.lang.ClassLoader.getResource(ClassLoader.java:1090)
	at java.lang.ClassLoader.getResource(ClassLoader.java:1088)
	at java.net.URLClassLoader.getResourceAsStream(URLClassLoader.java:232)
	at java.lang.Class.getResourceAsStream(Class.java:2223)
	at com.jcabi.xml.ClasspathResolver.resolveResource(ClasspathResolver.java:54)
	at com.sun.org.apache.xerces.internal.util.DOMEntityResolverWrapper.resolveEntity(DOMEntityResolverWrapper.java:117)
	at com.sun.org.apache.xerces.internal.impl.XMLEntityManager.resolveEntity(XMLEntityManager.java:1079)
	at com.sun.org.apache.xerces.internal.impl.xs.XMLSchemaLoader.resolveDocument(XMLSchemaLoader.java:660)
	at com.sun.org.apache.xerces.internal.impl.xs.XMLSchemaValidator.findSchemaGrammar(XMLSchemaValidator.java:2437)
	at com.sun.org.apache.xerces.internal.impl.xs.XMLSchemaValidator.handleStartElement(XMLSchemaValidator.java:1773)
	at com.sun.org.apache.xerces.internal.impl.xs.XMLSchemaValidator.startElement(XMLSchemaValidator.java:746)
	at com.sun.org.apache.xerces.internal.jaxp.validation.DOMValidatorHelper.beginNode(DOMValidatorHelper.java:277)
	at com.sun.org.apache.xerces.internal.jaxp.validation.DOMValidatorHelper.validate(DOMValidatorHelper.java:244)
	at com.sun.org.apache.xerces.internal.jaxp.validation.DOMValidatorHelper.validate(DOMValidatorHelper.java:190)
	at com.sun.org.apache.xerces.internal.jaxp.validation.ValidatorImpl.validate(ValidatorImpl.java:109)
	at javax.xml.validation.Validator.validate(Validator.java:124)
	at com.jcabi.xml.StrictXML.validate(StrictXML.java:221)
	at com.jcabi.xml.StrictXML.<init>(StrictXML.java:86)
	at com.jcabi.xml.StrictXML.<init>(StrictXML.java:75)
	at com.qulice.xml.XmlValidatorTest.failsValidation(XmlValidatorTest.java:292)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:47)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
	at org.junit.internal.runners.statements.ExpectException.evaluate(ExpectException.java:19)
	... 15 more
```

The following test passes (i.e. it properly throws `IllegalArgumentException`):
```java
    @Test(expected = IllegalArgumentException.class)
    public void failsValidationForInvalidURI() throws Exception {
        new StrictXML(
            new XMLDocument("<a xsi:schemaLocation=\"http://hello world\"></a>")
        );
    }
```

We should fix it. None of our code should throw `NullPointerException`, it is too vague and useless.

**Comment by dmarkov** [comment]
@yegor256 dispatch this issue please, see [par.21](http://at.teamed.io/policy.html#21)

**Comment by dmarkov** [comment]
@carlosmiranda thanks for the ticket, your account was topped for 15 mins, payment 71811380

**Comment by krzyk** [comment]
@yegor256 could we dispatch this one? It is (at least looks like) the root cause of https://github.com/teamed/qulice/issues/498

**Comment by yegor256** [comment]
@dmarkov assign @dmzaytsev here pls

**Comment by dmzaytsev** [comment]
@dmarkov PR #104 ready for review

**Comment by dmarkov** [comment]
> @dmarkov assign @dmzaytsev here pls

@yegor256 OK @dmzaytsev please proceed, this task is yours

**Comment by dmzaytsev** [comment]
@carlosmiranda fixed in #104 please close if alright

**Comment by carlosmiranda** [comment]
@dmzaytsev thanks!

**Comment by carlosmiranda** [comment]
@yegor256 can we do a bugfix release for this?

**Comment by yegor256** [comment]
@rultor release, tag is `0.17.1`

**Comment by dmarkov** [comment]
@dmzaytsev paid, thanks, added **1 hour** to your account, payment `73992099`, 22 hours was spent

there is a bonus for fast delivery (m=1320)

+60 added to your rating, current score is: [+1489](http://www.netbout.com/b/35166?open=rating)
